#
# Development only
#

version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: neftie-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: neftie
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: neftie
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    container_name: neftie-pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret

volumes:
  postgres:
