name: Backend Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - apps/backend/**
      - packages/api-client/**
      - packages/common/**
      - packages/prisma/**
      - packages/contracts/**
      - packages/subgraph/**
      - .github/workflows/backend-deploy.yml
      - .yarn.lock
    branches:
      - main

#
# Avoid the same workflow running more
# than once at the same time
#
concurrency:
  group: backend-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build image
        id: build
        uses: docker/build-push-action@v2
        timeout-minutes: 20
        with:
          context: .
          file: apps/backend/Dockerfile
          tags: ${{ secrets.REGISTRY_SERVER }}/neftie-backend:latest
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Deploy to Dokku
        uses: appleboy/ssh-action@master
        env:
          image-name: ${{ secrets.REGISTRY_SERVER }}/neftie-backend@${{ needs.docker-build.outputs.digest }}
        with:
          host: ${{ secrets.DOKKU_SSH_HOST }}
          username: ${{ secrets.DOKKU_SSH_USER }}
          key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            git:from-image backend ${{ env.image-name }}
