name: Contracts CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - packages/contracts/**
      - .github/workflows/contracts-ci.yml
      - .yarn.lock
    branches:
      - main

#
# Avoid the same workflow running more
# than once at the same time
#
concurrency:
  group: admin-cs-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  #
  # Cache yarn dependencies by hashing
  # the yarn.lock file. This allows for
  # much faster installs.
  #
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile

  #
  # Run contracts tests
  #

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run tests
        run: |
          yarn cs compile
          yarn cs test
