name: Frontend CI

on:
  workflow_dispatch:
  push:
    paths:
      - apps/frontend/**
      - packages/api-client/**
      - packages/common/**
      - packages/contracts/**
      - .github/workflows/frontend-ci.yml
      - .yarn.lock
    branches:
      - main
  pull_request:
    paths:
      - apps/frontend/**
      - packages/api-client/**
      - packages/common/**
      - packages/contracts/**
      - .github/workflows/frontend-ci.yml
      - .yarn.lock
    branches:
      - main

jobs:
  #
  # Cache yarn dependencies by hashing
  # the yarn.lock file. This allows for
  # much faster installs.
  #
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile

  #
  # Runs Prettier
  #
  format:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Format
        run: |
          yarn fe format

  #
  # Build the frontend, which also typechecks and runs
  # ESLint
  #
  build:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Restore yarn dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          yarn cs build
          yarn sg codegen:all
          yarn sg build
          yarn cm build
          yarn ac build
          yarn fe build
